rvm:
  - 1.8.7
  - 1.9.3
#  - ruby-head
  - jruby
  - rbx-18mode
  - rbx-19mode
services:
  - riak
  - couchdb
  - redis-server
  - cassandra
  - memcached
  - mongodb
before_install:
  - sudo apt-get install -qq libtokyocabinet8 libtokyocabinet-dev liblzo2-dev libtdb-dev
  - script/install-bundle.rb
env:
  global:
    - secure: "bNtinRuxS/FLP1fKj7KtHweIP/fG94CusdYKH/sBL6P0aqL3mr/dkbC34pSk\nNGkLKs/FAzvLkOo7aIOcCLx1WnL9yaZ12tmHgH8Ztf8ci2S52HSfqYwQw/dE\nq7euNMZVjvWfVu+15+Xpn6+t2XSubSO/TELfymDFGbhivmKAo5M="
    - secure: "Pv/MUnoaZMbPNB3vx4Hw2ASQBsUO7HIjJsfGHAQa5VbWlX3qEfMdezlYzNbf\nDPdpeabQwEwCUcINT7x10XKH5M4nZn6bBGfpvmNMxvZ8De1Et7mrwvb5/o73\n5EkyvYuUu8FB/LQmjB/4zZcjLQWNCtcfPlYPs7YcADBt0gIwn8M="
  matrix:
    - "TASK=test:parallel"
    - "TASK=test:non_parallel"
    - "TASK=benchmarks CONFIG=uniform_small"
    - "TASK=benchmarks CONFIG=uniform_medium"
    - "TASK=benchmarks CONFIG=uniform_large"
    - "TASK=benchmarks CONFIG=normal_small"
    - "TASK=benchmarks CONFIG=normal_medium"
    - "TASK=benchmarks CONFIG=normal_large"
matrix:
  allow_failures:
#    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-18mode
    - rvm: rbx-19mode
  # Parallel tests do not work on jruby
  exclude:
    - rvm: jruby
      env: "TASK=test:parallel"
    - rvm: jruby
      env: "TASK=benchmarks CONFIG=uniform_small"
    - rvm: jruby
      env: "TASK=benchmarks CONFIG=uniform_medium"
    - rvm: jruby
      env: "TASK=benchmarks CONFIG=uniform_large"
    - rvm: jruby
      env: "TASK=benchmarks CONFIG=normal_small"
    - rvm: jruby
      env: "TASK=benchmarks CONFIG=normal_medium"
    - rvm: jruby
      env: "TASK=benchmarks CONFIG=normal_large"
    - rvm: rbx-18mode
      env: "TASK=benchmarks CONFIG=uniform_small"
    - rvm: rbx-18mode
      env: "TASK=benchmarks CONFIG=uniform_medium"
    - rvm: rbx-18mode
      env: "TASK=benchmarks CONFIG=uniform_large"
    - rvm: rbx-18mode
      env: "TASK=benchmarks CONFIG=normal_small"
    - rvm: rbx-18mode
      env: "TASK=benchmarks CONFIG=normal_medium"
    - rvm: rbx-18mode
      env: "TASK=benchmarks CONFIG=normal_large"
    - rvm: rbx-19mode
      env: "TASK=benchmarks CONFIG=uniform_small"
    - rvm: rbx-19mode
      env: "TASK=benchmarks CONFIG=uniform_medium"
    - rvm: rbx-19mode
      env: "TASK=benchmarks CONFIG=uniform_large"
    - rvm: rbx-19mode
      env: "TASK=benchmarks CONFIG=normal_small"
    - rvm: rbx-19mode
      env: "TASK=benchmarks CONFIG=normal_medium"
    - rvm: rbx-19mode
      env: "TASK=benchmarks CONFIG=normal_large"
script: "bundle exec rake $TASK"
