language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-19mode
  - jruby-18mode
  - rbx-19mode
  - rbx-18mode
before_install:
  - script/kill-travis
  #- script/install-kyotocabinet
  - sudo apt-get install -qq libtokyocabinet8 libtokyocabinet-dev liblzo2-dev libtdb-dev libleveldb-dev tokyotyrant
  - script/start-services
  - script/install-bundle
  - script/upload-bundle
  - script/wait-services
install: 'echo "Bundle installed"'
before_script:
  - mysql -e 'create database moneta;'
  - mysql -e 'create database moneta_activerecord1;'
  - mysql -e 'create database moneta_activerecord2;'
env:
  global:
    - secure: "dtM4n7FP8P0UI9Iq+nsvQ7/yfDqsxhfCO9i8zMxm/f9Kxj5Z/4C7jsXsLA+e\n/7FZ9+ld2QjPSPU0LUiDpj/z81bxyZHwqocQ7Nb0DVvO3JRHpr4/iBQQQHd3\n0jvou3mRbu5mBlUjf1/ALaZA+b+vcnsF9fd86UnkY+ChriylGnM="
  matrix:
    - "TASK=test TEST_GROUP=1/10"
    - "TASK=test TEST_GROUP=2/10"
    - "TASK=test TEST_GROUP=3/10"
    - "TASK=test TEST_GROUP=4/10"
    - "TASK=test TEST_GROUP=5/10"
    - "TASK=test TEST_GROUP=6/10"
    - "TASK=test TEST_GROUP=7/10"
    - "TASK=test TEST_GROUP=8/10"
    - "TASK=test TEST_GROUP=9/10"
    - "TASK=test TEST_GROUP=10/10"
    - "TASK=test TEST_GROUP=unstable"
    - "TASK=benchmarks CONFIG=uniform_small"
    - "TASK=benchmarks CONFIG=uniform_medium"
    - "TASK=benchmarks CONFIG=uniform_large"
    - "TASK=benchmarks CONFIG=normal_small"
    - "TASK=benchmarks CONFIG=normal_medium"
    - "TASK=benchmarks CONFIG=normal_large"
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - env: "TASK=test TEST_GROUP=unstable"
script: "bundle exec rake $TASK"
branches:
  only:
    - master
    - travis
