language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
#  - rbx-18mode
#  - rbx-19mode
before_install:
  - script/kill-travis
  - script/install-kyotocabinet
  - sudo apt-get install -qq libtokyocabinet8 libtokyocabinet-dev liblzo2-dev libtdb-dev tokyotyrant
  - script/start-services
  - script/install-bundle
  - script/upload-bundle
install: 'echo "Bundle installed"'
before_script:
  - mysql -e 'create database moneta;'
env:
  global:
    - secure: "B0vx1g1CB1A6mM3B/iy2ATicfS4OXT80bb2RVe8mSRsPzez1B4q4Q4hJcaMI\nrMARONN8Krtnti+IqvmDnB0Z0AKYMEyIc+zT37zJOCjLdkLJl+x/thuU/MbC\nvlLVwjMf6JE2EUzTfORDRFYc5ycCqfsfgNk1Go0D2CPT6P9u9uQ="
  matrix:
    - "TASK=test TEST_GROUP=1/5"
    - "TASK=test TEST_GROUP=2/5"
    - "TASK=test TEST_GROUP=3/5"
    - "TASK=test TEST_GROUP=4/5"
    - "TASK=test TEST_GROUP=5/5"
    - "TASK=test TEST_GROUP=unstable"
    - "TASK=benchmarks CONFIG=uniform_small"
    - "TASK=benchmarks CONFIG=uniform_medium"
    - "TASK=benchmarks CONFIG=uniform_large"
    - "TASK=benchmarks CONFIG=normal_small"
    - "TASK=benchmarks CONFIG=normal_medium"
    - "TASK=benchmarks CONFIG=normal_large"
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - env:
      - "TASK=test TEST_GROUP=unstable"
      - secure: "B0vx1g1CB1A6mM3B/iy2ATicfS4OXT80bb2RVe8mSRsPzez1B4q4Q4hJcaMI\nrMARONN8Krtnti+IqvmDnB0Z0AKYMEyIc+zT37zJOCjLdkLJl+x/thuU/MbC\nvlLVwjMf6JE2EUzTfORDRFYc5ycCqfsfgNk1Go0D2CPT6P9u9uQ="
script: "bundle exec rake $TASK"
branches:
  only:
    - master
    - travis
